version: 2.0
jobs:
  build:

    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    branches:
      only:
        - master

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run lint
      - run: npm run gh-pages
      - deploy:
          command: |
            git config user.name $GITHUB_NAME
            git config user.email $GITHUB_EMAIL
            npm run deploy
